workflows:
  android-production:
    name: Fat7i Android APK (Production)

    max_build_duration: 60

    environment:
      flutter: 3.41.5
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
        ANDROID_NDK_VERSION: "28.2.13676358"
        ANDROID_NDK_HOME: "/usr/local/share/android-sdk/ndk/28.2.13676358"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        # - /usr/local/share/android-sdk/ndk

    scripts:
      - name: Get Dependencies
        script: flutter pub get

      - name: Build APK (Production)
        # flutter build apk --release --obfuscate --split-debug-info=build/debug-info
        script: |
          flutter build apk \
            --release \
            --flavor production \
            -t lib/main.dart \
            --obfuscate \
            --split-debug-info=build/debug-info
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - fat7ighareeb@gmail.com
          # - fat7ighareeb@gmail.com
          # - amiradelsaad@gmail.com
          # - me@aminuix.com
        notify:
          success: true
          failure: false
